version: '3'

services:
    db:
        container_name: db
        image: mariadb:10.3.9
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql

    php:
        container_name: php
        build: ./docker/php
        volumes:
            - .:/var/www/html
        ports:
            - 9000:9000

    nginx:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www/html
        ports:
            - 8080:80

volumes:
    dbdata:
        driver: local